#!/bin/sh

echo "$(sed '0,/^__DATA__$/d' "$0")" | dmenu | cut -d " " -f1 | tr "\n" " " | wl-copy

exit

__DATA__
😀 Grinning face
😃 Smiling face with open mouth
😄 Smiling face with open mouth and smiling eyes
😁 Grinning face with smiling eyes
😅 Smiling face with open mouth and cold sweat
😂 Face with tears of joy
🤣 Rolling on the floor laughing
☺️ White smiling face
😊 Smiling face with smiling eyes
😇 Smiling face with halo
🙂 Slightly smiling face
🙃 Upside-down face
😉 Winking face
😌 Relieved face
😍 Smiling face with heart-shaped eyes
😘 Face throwing a kiss
😗 Kissing face
😙 Kissing face with smiling eyes
😚 Kissing face with closed eyes
😋 Face savouring delicious food
😜 Face with stuck-out tongue and winking eye
😛 Face with stuck-out tongue
🤑 Money-mouth face
🤗 Hugging face
🤓 Nerd face
😎 Smiling face with sunglasses
🤡 Clown face
🤠 Face with cowboy hat
😏 Smirking face
😒 Unamused face
😞 Disappointed face
😔 Pensive face
😟 Worried face
😕 Confused face
🙁 Slightly frowning face
☹️ White frowning face
😣 Persevering face
😖 Confounded face
😫 Tired face
😩 Weary face
😤 Face with look of triumph
😠 Angry face
😡 Pouting face
😶 Face without mouth
😐 Neutral face
😑 Expressionless face
😯 Hushed face
😦 Frowning face with open mouth
😧 Anguished face
😮 Face with open mouth
😲 Astonished face
😵 Dizzy face
😳 Flushed face
😱 Face screaming in fear
😨 Fearful face
😰 Face with open mouth and cold sweat
😢 Crying face
😥 Disappointed but relieved face
🤤 Drooling face
😭 Loudly crying face
😓 Face with cold sweat
😪 Sleepy face
😴 Sleeping face
🙄 Face with rolling eyes
🤔 Thinking face
🤥 Lying face
😬 Grimacing face
🤐 Zipper-mouth face
🤢 Nauseated face
🤧 Sneezing face
😷 Face with medical mask
🤒 Face with thermometer
🤕 Face with head-bandage
😈 Smiling face with horns
👿 Imp
👹 Japanese ogre
👺 Japanese goblin
💩 Pile of poo
👻 Ghost
💀 Skull
☠️ Skull and crossbones
👽 Extraterrestrial alien
👾 Alien monster
🤖 Robot face
🎃 Jack-o-lantern
😺 Smiling cat face with open mouth
😸 Grinning cat face with smiling eyes
😹 Cat face with tears of joy
😻 Smiling cat face with heart-shaped eyes
😼 Cat face with wry smile
😽 Kissing cat face with closed eyes
🙀 Weary cat face
😿 Crying cat face
😾 Pouting cat face
👐 Open hands sign
🙌 Person raising both hands in celebration
👏 Clapping hands sign
🙏 Person with folded hands
🤝 Handshake
👍 Thumbs up sign
👎 Thumbs down sign
👊 Fisted hand sign
✊ Raised fist
🤛 Left-facing fist
🤜 Right-facing fist
🤞 Hand with index and middle fingers crossed
✌️ Victory hand
🤘 Sign of the horns
👌 Ok hand sign
👈 White left pointing backhand index
👉 White right pointing backhand index
👆 White up pointing backhand index
👇 White down pointing backhand index
☝️ White up pointing index
✋ Raised hand
🤚 Raised back of hand
🖐 Raised hand with fingers splayed
👋 Waving hand sign
🤙 Call me hand
💪 Flexed biceps
🖕 Reversed hand with middle finger extended
✍️ Writing hand
🤳 Selfie
💅 Nail polish
💍 Ring
💄 Lipstick
💋 Kiss mark
👄 Mouth
👅 Tongue
👂 Ear
👃 Nose
👣 Footprints
👁 Eye
👀 Eyes
🗣 Speaking head in silhouette
👤 Bust in silhouette
👥 Busts in silhouette
👶 Baby
👦 Boy
👧 Girl
👨 Man
👩 Woman
👱 Person with blond hair
👱 Person with blond hair
👴 Older man
👵 Older woman
👲 Man with gua pi mao
👳 Man with turban
👳 Man with turban
👮 Police officer
👮 Police officer
👷 Construction worker
👷 Construction worker
💂 Guardsman
💂 Guardsman
🕵️ Sleuth or spy
🕵️ Sleuth or spy
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
👩 Woman
👨 Man
🤶 Mother christmas
🎅 Father christmas
👸 Princess
🤴 Prince
👰 Bride with veil
🤵 Man in tuxedo
👼 Baby angel
🤰 Pregnant woman
🙇 Person bowing deeply
🙇 Person bowing deeply
💁 Information desk person
💁 Information desk person
🙅 Face with no good gesture
🙅 Face with no good gesture
🙆 Face with ok gesture
🙆 Face with ok gesture
🙋 Happy person raising one hand
🙋 Happy person raising one hand
🤦 Face palm
🤦 Face palm
🤷 Shrug
🤷 Shrug
🙎 Person with pouting face
🙎 Person with pouting face
🙍 Person frowning
🙍 Person frowning
💇 Haircut
💇 Haircut
💆 Face massage
💆 Face massage
🕴 Man in business suit levitating
💃 Dancer
🕺 Man dancing
👯 Woman with bunny ears
👯 Woman with bunny ears
🚶 Pedestrian
🚶 Pedestrian
🏃 Runner
🏃 Runner
👫 Man and woman holding hands
👭 Two women holding hands
👬 Two men holding hands
💑 Couple with heart
👩 Woman
👨 Man
💏 Kiss
👩 Woman
👨 Man
👪 Family
👨 Man
👨 Man
👨 Man
👨 Man
👩 Woman
👩 Woman
👩 Woman
👩 Woman
👩 Woman
👨 Man
👨 Man
👨 Man
👨 Man
👨 Man
👩 Woman
👩 Woman
👩 Woman
👩 Woman
👩 Woman
👨 Man
👨 Man
👨 Man
👨 Man
👨 Man
👚 Womans clothes
👕 T-shirt
👖 Jeans
👔 Necktie
👗 Dress
👙 Bikini
👘 Kimono
👠 High-heeled shoe
👡 Womans sandal
👢 Womans boots
👞 Mans shoe
👟 Athletic shoe
👒 Womans hat
🎩 Top hat
🎓 Graduation cap
👑 Crown
⛑ Helmet with white cross
🎒 School satchel
👝 Pouch
👛 Purse
👜 Handbag
💼 Briefcase
👓 Eyeglasses
🕶 Dark sunglasses
🌂 Closed umbrella
☂️ Umbrella
⚽️ Soccer ball
🏀 Basketball and hoop
🏈 American football
⚾️ Baseball
🎾 Tennis racquet and ball
🏐 Volleyball
🏉 Rugby football
🎱 Billiards
🏓 Table tennis paddle and ball
🏸 Badminton racquet and shuttlecock
🥅 Goal net
🏒 Ice hockey stick and puck
🏑 Field hockey stick and ball
🏏 Cricket bat and ball
⛳️ Flag in hole
🏹 Bow and arrow
🎣 Fishing pole and fish
🥊 Boxing glove
🥋 Martial arts uniform
⛸ Ice skate
🎿 Ski and ski boot
⛷ Skier
🏂 Snowboarder
🏋️ Weight lifter
🏋️ Weight lifter
🤺 Fencer
🤼 Wrestlers
🤼 Wrestlers
🤸 Person doing cartwheel
🤸 Person doing cartwheel
⛹️ Person with ball
⛹️ Person with ball
🤾 Handball
🤾 Handball
🏌️ Golfer
🏌️ Golfer
🏄 Surfer
🏄 Surfer
🏊 Swimmer
🏊 Swimmer
🤽 Water polo
🤽 Water polo
🚣 Rowboat
🚣 Rowboat
🏇 Horse racing
🚴 Bicyclist
🚴 Bicyclist
🚵 Mountain bicyclist
🚵 Mountain bicyclist
🎽 Running shirt with sash
🏅 Sports medal
🎖 Military medal
🥇 First place medal
🥈 Second place medal
🥉 Third place medal
🏆 Trophy
🏵 Rosette
🎗 Reminder ribbon
🎫 Ticket
🎟 Admission tickets
🎪 Circus tent
🤹 Juggling
🤹 Juggling
🎭 Performing arts
🎨 Artist palette
🎬 Clapper board
🎤 Microphone
🎧 Headphone
🎼 Musical score
🎹 Musical keyboard
🥁 Drum with drumsticks
🎷 Saxophone
🎺 Trumpet
🎸 Guitar
🎻 Violin
🎲 Game die
🎯 Direct hit
🎳 Bowling
🎮 Video game
🎰 Slot machine
🚗 Automobile
🚕 Taxi
🚙 Recreational vehicle
🚌 Bus
🚎 Trolleybus
🏎 Racing car
🚓 Police car
🚑 Ambulance
🚒 Fire engine
🚐 Minibus
🚚 Delivery truck
🚛 Articulated lorry
🚜 Tractor
🛴 Scooter
🚲 Bicycle
🛵 Motor scooter
🏍 Racing motorcycle
🚨 Police cars revolving light
🚔 Oncoming police car
🚍 Oncoming bus
🚘 Oncoming automobile
🚖 Oncoming taxi
🚡 Aerial tramway
🚠 Mountain cableway
🚟 Suspension railway
🚃 Railway car
🚋 Tram car
🚞 Mountain railway
🚝 Monorail
🚄 High-speed train
🚅 High-speed train with bullet nose
🚈 Light rail
🚂 Steam locomotive
🚆 Train
🚇 Metro
🚊 Tram
🚉 Station
🚁 Helicopter
🛩 Small airplane
✈️ Airplane
🛫 Airplane departure
🛬 Airplane arriving
🚀 Rocket
🛰 Satellite
💺 Seat
🛶 Canoe
⛵️ Sailboat
🛥 Motor boat
🚤 Speedboat
🛳 Passenger ship
⛴ Ferry
🚢 Ship
⚓️ Anchor
🚧 Construction sign
⛽️ Fuel pump
🚏 Bus stop
🚦 Vertical traffic light
🚥 Horizontal traffic light
🗺 World map
🗿 Moyai
🗽 Statue of liberty
⛲️ Fountain
🗼 Tokyo tower
🏰 European castle
🏯 Japanese castle
🏟 Stadium
🎡 Ferris wheel
🎢 Roller coaster
🎠 Carousel horse
⛱ Umbrella on ground
🏖 Beach with umbrella
🏝 Desert island
⛰ Mountain
🏔 Snow capped mountain
🗻 Mount fuji
🌋 Volcano
🏜 Desert
🏕 Camping
⛺️ Tent
🛤 Railway track
🛣 Motorway
🏗 Building construction
🏭 Factory
🏠 House building
🏡 House with garden
🏘 House buildings
🏚 Derelict house building
🏢 Office building
🏬 Department store
🏣 Japanese post office
🏤 European post office
🏥 Hospital
🏦 Bank
🏨 Hotel
🏪 Convenience store
🏫 School
🏩 Love hotel
💒 Wedding
🏛 Classical building
⛪️ Church
🕌 Mosque
🕍 Synagogue
🕋 Kaaba
⛩ Shinto shrine
🗾 Silhouette of japan
🎑 Moon viewing ceremony
🏞 National park
🌅 Sunrise
🌄 Sunrise over mountains
🌠 Shooting star
🎇 Firework sparkler
🎆 Fireworks
🌇 Sunset over buildings
🌆 Cityscape at dusk
🏙 Cityscape
🌃 Night with stars
🌌 Milky way
🌉 Bridge at night
🌁 Foggy
🐶 Dog face
🐱 Cat face
🐭 Mouse face
🐹 Hamster face
🐰 Rabbit face
🦊 Fox face
🐻 Bear face
🐼 Panda face
🐨 Koala
🐯 Tiger face
🦁 Lion face
🐮 Cow face
🐷 Pig face
🐽 Pig nose
🐸 Frog face
🐵 Monkey face
🙈 See-no-evil monkey
🙉 Hear-no-evil monkey
🙊 Speak-no-evil monkey
🐒 Monkey
🐔 Chicken
🐧 Penguin
🐦 Bird
🐤 Baby chick
🐣 Hatching chick
🐥 Front-facing baby chick
🦆 Duck
🦅 Eagle
🦉 Owl
🦇 Bat
🐺 Wolf face
🐗 Boar
🐴 Horse face
🦄 Unicorn face
🐝 Honeybee
🐛 Bug
🦋 Butterfly
🐌 Snail
🐚 Spiral shell
🐞 Lady beetle
🐜 Ant
🕷 Spider
🕸 Spider web
🐢 Turtle
🐍 Snake
🦎 Lizard
🦂 Scorpion
🦀 Crab
🦑 Squid
🐙 Octopus
🦐 Shrimp
🐠 Tropical fish
🐟 Fish
🐡 Blowfish
🐬 Dolphin
🦈 Shark
🐳 Spouting whale
🐋 Whale
🐊 Crocodile
🐆 Leopard
🐅 Tiger
🐃 Water buffalo
🐂 Ox
🐄 Cow
🦌 Deer
🐪 Dromedary camel
🐫 Bactrian camel
🐘 Elephant
🦏 Rhinoceros
🦍 Gorilla
🐎 Horse
🐖 Pig
🐐 Goat
🐏 Ram
🐑 Sheep
🐕 Dog
🐩 Poodle
🐈 Cat
🐓 Rooster
🦃 Turkey
🕊 Dove of peace
🐇 Rabbit
🐁 Mouse
🐀 Rat
🐿 Chipmunk
🐾 Paw prints
🐉 Dragon
🐲 Dragon face
🌵 Cactus
🎄 Christmas tree
🌲 Evergreen tree
🌳 Deciduous tree
🌴 Palm tree
🌱 Seedling
🌿 Herb
☘️ Shamrock
🍀 Four leaf clover
🎍 Pine decoration
🎋 Tanabata tree
🍃 Leaf fluttering in wind
🍂 Fallen leaf
🍁 Maple leaf
🍄 Mushroom
🌾 Ear of rice
💐 Bouquet
🌷 Tulip
🌹 Rose
🥀 Wilted flower
🌻 Sunflower
🌼 Blossom
🌸 Cherry blossom
🌺 Hibiscus
🌎 Earth globe americas
🌍 Earth globe europe-africa
🌏 Earth globe asia-australia
🌕 Full moon symbol
🌖 Waning gibbous moon symbol
🌗 Last quarter moon symbol
🌘 Waning crescent moon symbol
🌑 New moon symbol
🌒 Waxing crescent moon symbol
🌓 First quarter moon symbol
🌔 Waxing gibbous moon symbol
🌚 New moon with face
🌝 Full moon with face
🌞 Sun with face
🌛 First quarter moon with face
🌜 Last quarter moon with face
🌙 Crescent moon
💫 Dizzy symbol
⭐️ White medium star
🌟 Glowing star
✨ Sparkles
⚡️ High voltage sign
🔥 Fire
💥 Collision symbol
☄️ Comet
☀️ Black sun with rays
🌤 White sun with small cloud
⛅️ Sun behind cloud
🌥 White sun behind cloud
🌦 White sun behind cloud with rain
🌈 Rainbow
☁️ Cloud
🌧 Cloud with rain
⛈ Thunder cloud and rain
🌩 Cloud with lightning
🌨 Cloud with snow
☃️ Snowman
⛄️ Snowman without snow
❄️ Snowflake
🌬 Wind blowing face
💨 Dash symbol
🌪 Cloud with tornado
🌫 Fog
🌊 Water wave
💧 Droplet
💦 Splashing sweat symbol
☔️ Umbrella with rain drops
⌚️ Watch
📱 Mobile phone
📲 Mobile phone with rightwards arrow at left
💻 Personal computer
⌨️ Keyboard
🖥 Desktop computer
🖨 Printer
🖱 Three button mouse
🖲 Trackball
🕹 Joystick
🗜 Compression
💽 Minidisc
💾 Floppy disk
💿 Optical disc
📀 Dvd
📼 Videocassette
📷 Camera
📸 Camera with flash
📹 Video camera
🎥 Movie camera
📽 Film projector
🎞 Film frames
📞 Telephone receiver
☎️ Black telephone
📟 Pager
📠 Fax machine
📺 Television
📻 Radio
🎙 Studio microphone
🎚 Level slider
🎛 Control knobs
⏱ Stopwatch
⏲ Timer clock
⏰ Alarm clock
🕰 Mantelpiece clock
⌛️ Hourglass
⏳ Hourglass with flowing sand
📡 Satellite antenna
🔋 Battery
🔌 Electric plug
💡 Electric light bulb
🔦 Electric torch
🕯 Candle
🗑 Wastebasket
🛢 Oil drum
💸 Money with wings
💵 Banknote with dollar sign
💴 Banknote with yen sign
💶 Banknote with euro sign
💷 Banknote with pound sign
💰 Money bag
💳 Credit card
💎 Gem stone
⚖️ Scales
🔧 Wrench
🔨 Hammer
⚒ Hammer and pick
🛠 Hammer and wrench
⛏ Pick
🔩 Nut and bolt
⚙️ Gear
⛓ Chains
🔫 Pistol
💣 Bomb
🔪 Hocho
🗡 Dagger knife
⚔️ Crossed swords
🛡 Shield
🚬 Smoking symbol
⚰️ Coffin
⚱️ Funeral urn
🏺 Amphora
🔮 Crystal ball
📿 Prayer beads
💈 Barber pole
⚗️ Alembic
🔭 Telescope
🔬 Microscope
🕳 Hole
💊 Pill
💉 Syringe
🌡 Thermometer
🚽 Toilet
🚰 Potable water symbol
🚿 Shower
🛁 Bathtub
🛀 Bath
🛎 Bellhop bell
🔑 Key
🗝 Old key
🚪 Door
🛋 Couch and lamp
🛏 Bed
🛌 Sleeping accommodation
🖼 Frame with picture
🛍 Shopping bags
🛒 Shopping trolley
🎁 Wrapped present
🎈 Balloon
🎏 Carp streamer
🎀 Ribbon
🎊 Confetti ball
🎉 Party popper
🎎 Japanese dolls
🏮 Izakaya lantern
🎐 Wind chime
✉️ Envelope
📩 Envelope with downwards arrow above
📨 Incoming envelope
📧 E-mail symbol
💌 Love letter
📥 Inbox tray
📤 Outbox tray
📦 Package
🏷 Label
📪 Closed mailbox with lowered flag
📫 Closed mailbox with raised flag
📬 Open mailbox with raised flag
📭 Open mailbox with lowered flag
📮 Postbox
📯 Postal horn
📜 Scroll
📃 Page with curl
📄 Page facing up
📑 Bookmark tabs
📊 Bar chart
📈 Chart with upwards trend
📉 Chart with downwards trend
🗒 Spiral note pad
🗓 Spiral calendar pad
📆 Tear-off calendar
📅 Calendar
📇 Card index
🗃 Card file box
🗳 Ballot box with ballot
🗄 File cabinet
📋 Clipboard
📁 File folder
📂 Open file folder
🗂 Card index dividers
🗞 Rolled-up newspaper
📰 Newspaper
📓 Notebook
📔 Notebook with decorative cover
📒 Ledger
📕 Closed book
📗 Green book
📘 Blue book
📙 Orange book
📚 Books
📖 Open book
🔖 Bookmark
🔗 Link symbol
📎 Paperclip
🖇 Linked paperclips
📐 Triangular ruler
📏 Straight ruler
📌 Pushpin
📍 Round pushpin
✂️ Black scissors
🖊 Lower left ballpoint pen
🖋 Lower left fountain pen
✒️ Black nib
🖌 Lower left paintbrush
🖍 Lower left crayon
📝 Memo
✏️ Pencil
🔍 Left-pointing magnifying glass
🔎 Right-pointing magnifying glass
🔏 Lock with ink pen
🔐 Closed lock with key
🔒 Lock
🔓 Open lock
🍏 Green apple
🍎 Red apple
🍐 Pear
🍊 Tangerine
🍋 Lemon
🍌 Banana
🍉 Watermelon
🍇 Grapes
🍓 Strawberry
🍈 Melon
🍒 Cherries
🍑 Peach
🍍 Pineapple
🥝 Kiwifruit
🥑 Avocado
🍅 Tomato
🍆 Aubergine
🥒 Cucumber
🥕 Carrot
🌽 Ear of maize
🌶 Hot pepper
🥔 Potato
🍠 Roasted sweet potato
🌰 Chestnut
🥜 Peanuts
🍯 Honey pot
🥐 Croissant
🍞 Bread
🥖 Baguette bread
🧀 Cheese wedge
🥚 Egg
🍳 Cooking
🥓 Bacon
🥞 Pancakes
🍤 Fried shrimp
🍗 Poultry leg
🍖 Meat on bone
🍕 Slice of pizza
🌭 Hot dog
🍔 Hamburger
🍟 French fries
🥙 Stuffed flatbread
🌮 Taco
🌯 Burrito
🥗 Green salad
🥘 Shallow pan of food
🍝 Spaghetti
🍜 Steaming bowl
🍲 Pot of food
🍥 Fish cake with swirl design
🍣 Sushi
🍱 Bento box
🍛 Curry and rice
🍚 Cooked rice
🍙 Rice ball
🍘 Rice cracker
🍢 Oden
🍡 Dango
🍧 Shaved ice
🍨 Ice cream
🍦 Soft ice cream
🍰 Shortcake
🎂 Birthday cake
🍮 Custard
🍭 Lollipop
🍬 Candy
🍫 Chocolate bar
🍿 Popcorn
🍩 Doughnut
🍪 Cookie
🥛 Glass of milk
🍼 Baby bottle
☕️ Hot beverage
🍵 Teacup without handle
🍶 Sake bottle and cup
🍺 Beer mug
🍻 Clinking beer mugs
🥂 Clinking glasses
🍷 Wine glass
🥃 Tumbler glass
🍸 Cocktail glass
🍹 Tropical drink
🍾 Bottle with popping cork
🥄 Spoon
🍴 Fork and knife
🍽 Fork and knife with plate
❤️ Heavy black heart
💛 Yellow heart
💚 Green heart
💙 Blue heart
💜 Purple heart
🖤 Black heart
💔 Broken heart
❣️ Heavy heart exclamation mark ornament
💕 Two hearts
💞 Revolving hearts
💓 Beating heart
💗 Growing heart
💖 Sparkling heart
💘 Heart with arrow
💝 Heart with ribbon
💟 Heart decoration
☮️ Peace symbol
✝️ Latin cross
☪️ Star and crescent
🕉 Om symbol
☸️ Wheel of dharma
✡️ Star of david
🔯 Six pointed star with middle dot
🕎 Menorah with nine branches
☯️ Yin yang
☦️ Orthodox cross
🛐 Place of worship
⛎ Ophiuchus
♈️ Aries
♉️ Taurus
♊️ Gemini
♋️ Cancer
♌️ Leo
♍️ Virgo
♎️ Libra
♏️ Scorpius
♐️ Sagittarius
♑️ Capricorn
♒️ Aquarius
♓️ Pisces
🆔 Squared id
⚛️ Atom symbol
🉑 Circled ideograph accept
☢️ Radioactive sign
☣️ Biohazard sign
📴 Mobile phone off
📳 Vibration mode
🈶 Squared cjk unified ideograph-6709
🈚️ Squared cjk unified ideograph-7121
🈸 Squared cjk unified ideograph-7533
🈺 Squared cjk unified ideograph-55b6
🈷️ Squared cjk unified ideograph-6708
✴️ Eight pointed black star
🆚 Squared vs
💮 White flower
🉐 Circled ideograph advantage
㊙️ Circled ideograph secret
㊗️ Circled ideograph congratulation
🈴 Squared cjk unified ideograph-5408
🈵 Squared cjk unified ideograph-6e80
🈹 Squared cjk unified ideograph-5272
🈲 Squared cjk unified ideograph-7981
🅰️ Negative squared latin capital letter a
🅱️ Negative squared latin capital letter b
🆎 Negative squared ab
🆑 Squared cl
🅾️ Negative squared latin capital letter o
🆘 Squared sos
❌ Cross mark
⭕️ Heavy large circle
🛑 Octagonal sign
⛔️ No entry
📛 Name badge
🚫 No entry sign
💯 Hundred points symbol
💢 Anger symbol
♨️ Hot springs
🚷 No pedestrians
🚯 Do not litter symbol
🚳 No bicycles
🚱 Non-potable water symbol
🔞 No one under eighteen symbol
📵 No mobile phones
🚭 No smoking symbol
❗️ Heavy exclamation mark symbol
❕ White exclamation mark ornament
❓ Black question mark ornament
❔ White question mark ornament
‼️ Double exclamation mark
⁉️ Exclamation question mark
🔅 Low brightness symbol
🔆 High brightness symbol
〽️ Part alternation mark
⚠️ Warning sign
🚸 Children crossing
🔱 Trident emblem
⚜️ Fleur-de-lis
🔰 Japanese symbol for beginner
♻️ Black universal recycling symbol
✅ White heavy check mark
🈯️ Squared cjk unified ideograph-6307
💹 Chart with upwards trend and yen sign
❇️ Sparkle
✳️ Eight spoked asterisk
❎ Negative squared cross mark
🌐 Globe with meridians
💠 Diamond shape with a dot inside
Ⓜ️ Circled latin capital letter m
🌀 Cyclone
💤 Sleeping symbol
🏧 Automated teller machine
🚾 Water closet
♿️ Wheelchair symbol
🅿️ Negative squared latin capital letter p
🈳 Squared cjk unified ideograph-7a7a
🈂️ Squared katakana sa
🛂 Passport control
🛃 Customs
🛄 Baggage claim
🛅 Left luggage
🚹 Mens symbol
🚺 Womens symbol
🚼 Baby symbol
🚻 Restroom
🚮 Put litter in its place symbol
🎦 Cinema
📶 Antenna with bars
🈁 Squared katakana koko
🔣 Input symbol for symbols
ℹ️ Information source
🔤 Input symbol for latin letters
🔡 Input symbol for latin small letters
🔠 Input symbol for latin capital letters
🆖 Squared ng
🆗 Squared ok
🆙 Squared up with exclamation mark
🆒 Squared cool
🆕 Squared new
🆓 Squared free
🔟 Keycap ten
🔢 Input symbol for numbers
▶️ Black right-pointing triangle
⏸ Double vertical bar
⏹ Black square for stop
⏺ Black circle for record
⏩ Black right-pointing double triangle
⏪ Black left-pointing double triangle
⏫ Black up-pointing double triangle
⏬ Black down-pointing double triangle
◀️ Black left-pointing triangle
🔼 Up-pointing small red triangle
🔽 Down-pointing small red triangle
➡️ Black rightwards arrow
⬅️ Leftwards black arrow
⬆️ Upwards black arrow
⬇️ Downwards black arrow
↗️ North east arrow
↘️ South east arrow
↙️ South west arrow
↖️ North west arrow
↕️ Up down arrow
↔️ Left right arrow
↪️ Rightwards arrow with hook
↩️ Leftwards arrow with hook
⤴️ Arrow pointing rightwards then curving upwards
🔀 Twisted rightwards arrows
🎵 Musical note
🎶 Multiple musical notes
➕ Heavy plus sign
➖ Heavy minus sign
➗ Heavy division sign
✖️ Heavy multiplication x
💲 Heavy dollar sign
💱 Currency exchange
™️ Trade mark sign
©️ Copyright sign
®️ Registered sign
〰️ Wavy dash
➰ Curly loop
➿ Double curly loop
🔚 End with leftwards arrow above
🔙 Back with leftwards arrow above
🔝 Top with upwards arrow above
🔜 Soon with rightwards arrow above
✔️ Heavy check mark
☑️ Ballot box with check
🔘 Radio button
⚪️ Medium white circle
⚫️ Medium black circle
🔴 Large red circle
🔵 Large blue circle
🔺 Up-pointing red triangle
🔻 Down-pointing red triangle
🔸 Small orange diamond
🔹 Small blue diamond
🔶 Large orange diamond
🔷 Large blue diamond
🔳 White square button
🔲 Black square button
▪️ Black small square
▫️ White small square
◾️ Black medium small square
◽️ White medium small square
◼️ Black medium square
◻️ White medium square
⬛️ Black large square
⬜️ White large square
🔈 Speaker
🔇 Speaker with cancellation stroke
🔉 Speaker with one sound wave
🔊 Speaker with three sound waves
🔔 Bell
🔕 Bell with cancellation stroke
📣 Cheering megaphone
📢 Public address loudspeaker
👁 Eye
💬 Speech balloon
💭 Thought balloon
🗯 Right anger bubble
♠️ Black spade suit
♣️ Black club suit
♥️ Black heart suit
♦️ Black diamond suit
🃏 Playing card black joker
🎴 Flower playing cards
🀄️ Mahjong tile red dragon
🕐 Clock face one oclock
🕑 Clock face two oclock
🕒 Clock face three oclock
🕓 Clock face four oclock
🕔 Clock face five oclock
🕕 Clock face six oclock
🕖 Clock face seven oclock
🕗 Clock face eight oclock
🕘 Clock face nine oclock
🕙 Clock face ten oclock
🕚 Clock face eleven oclock
🕛 Clock face twelve oclock
🕜 Clock face one-thirty
🕝 Clock face two-thirty
🕞 Clock face three-thirty
🕟 Clock face four-thirty
🕠 Clock face five-thirty
🕡 Clock face six-thirty
🕢 Clock face seven-thirty
🕣 Clock face eight-thirty
🕤 Clock face nine-thirty
🕥 Clock face ten-thirty
🕦 Clock face eleven-thirty
🕧 Clock face twelve-thirty
🏳️ Waving white flag
🏴 Waving black flag
🏁 Chequered flag
🚩 Triangular flag on post
