#!/bin/sh

echo "$(sed '0,/^__DATA__$/d' "$0")" | dmenu | cut -d " " -f1 | tr "\n" " " | wl-copy

exit

__DATA__
😀 Grinning face
😃 Grinning face with big eyes
😄 Grinning face with smiling eyes
😁 Beaming face with smiling eyes
😆 Grinning squinting face
😅 Grinning face with sweat
🤣 Rolling on the floor laughing
😂 Face with tears of joy
🙂 Slightly smiling face
🙃 Upside-down face
🫠 Melting face
😉 Winking face
😊 Smiling face with smiling eyes
😇 Smiling face with halo
🥰 Smiling face with hearts
😍 Smiling face with heart-eyes
🤩 Star-struck
😘 Face blowing a kiss
😗 Kissing face
☺ Smiling face
😚 Kissing face with closed eyes
😙 Kissing face with smiling eyes
🥲 Smiling face with tear
😋 Face savoring food
😛 Face with tongue
😜 Winking face with tongue
🤪 Zany face
😝 Squinting face with tongue
🤑 Money-mouth face
🤗 Smiling face with open hands
🤭 Face with hand over mouth
🫢 Face with open eyes and hand over mouth
🫣 Face with peeking eye
🤫 Shushing face
🤔 Thinking face
🫡 Saluting face
🤐 Zipper-mouth face
🤨 Face with raised eyebrow
😐 Neutral face
😑 Expressionless face
😶 Face without mouth
🫥 Dotted line face
😶‍🌫️ face in clouds
😏 Smirking face
😒 Unamused face
🙄 Face with rolling eyes
😬 Grimacing face
😮‍💨 face exhaling
🤥 Lying face
🫨 Shaking face
🙂‍↔️ head shaking horizontally
🙂‍↕️ head shaking vertically
😌 Relieved face
😔 Pensive face
😪 Sleepy face
🤤 Drooling face
😴 Sleeping face
🫩 ⊛ face with bags under eyes
😷 Face with medical mask
🤒 Face with thermometer
🤕 Face with head-bandage
🤢 Nauseated face
🤮 Face vomiting
🤧 Sneezing face
🥵 Hot face
🥶 Cold face
🥴 Woozy face
😵 Face with crossed-out eyes
😵‍💫 face with spiral eyes
🤯 Exploding head
🤠 Cowboy hat face
🥳 Partying face
🥸 Disguised face
😎 Smiling face with sunglasses
🤓 Nerd face
🧐 Face with monocle
😕 Confused face
🫤 Face with diagonal mouth
😟 Worried face
🙁 Slightly frowning face
☹ Frowning face
😮 Face with open mouth
😯 Hushed face
😲 Astonished face
😳 Flushed face
🥺 Pleading face
🥹 Face holding back tears
😦 Frowning face with open mouth
😧 Anguished face
😨 Fearful face
😰 Anxious face with sweat
😥 Sad but relieved face
😢 Crying face
😭 Loudly crying face
😱 Face screaming in fear
😖 Confounded face
😣 Persevering face
😞 Disappointed face
😓 Downcast face with sweat
😩 Weary face
😫 Tired face
🥱 Yawning face
😤 Face with steam from nose
😡 Enraged face
😠 Angry face
🤬 Face with symbols on mouth
😈 Smiling face with horns
👿 Angry face with horns
💀 Skull
☠ Skull and crossbones
💩 Pile of poo
🤡 Clown face
👹 Ogre
👺 Goblin
👻 Ghost
👽 Alien
👾 Alien monster
🤖 Robot
😺 Grinning cat
😸 Grinning cat with smiling eyes
😹 Cat with tears of joy
😻 Smiling cat with heart-eyes
😼 Cat with wry smile
😽 Kissing cat
🙀 Weary cat
😿 Crying cat
😾 Pouting cat
🙈 See-no-evil monkey
🙉 Hear-no-evil monkey
🙊 Speak-no-evil monkey
💌 Love letter
💘 Heart with arrow
💝 Heart with ribbon
💖 Sparkling heart
💗 Growing heart
💓 Beating heart
💞 Revolving hearts
💕 Two hearts
💟 Heart decoration
❣ Heart exclamation
💔 Broken heart
❤️‍🔥 heart on fire
❤️‍🩹 mending heart
❤ Red heart
🩷 Pink heart
🧡 Orange heart
💛 Yellow heart
💚 Green heart
💙 Blue heart
🩵 Light blue heart
💜 Purple heart
🤎 Brown heart
🖤 Black heart
🩶 Grey heart
🤍 White heart
💋 Kiss mark
💯 Hundred points
💢 Anger symbol
💥 Collision
💫 Dizzy
💦 Sweat droplets
💨 Dashing away
🕳 Hole
💬 Speech balloon
👁️‍🗨️ eye in speech bubble
🗨 Left speech bubble
🗯 Right anger bubble
💭 Thought balloon
💤 zZZ
👋 Waving hand
🤚 Raised back of hand
🖐 Hand with fingers splayed
✋ Raised hand
🖖 Vulcan salute
🫱 Rightwards hand
🫲 Leftwards hand
🫳 Palm down hand
🫴 Palm up hand
🫷 Leftwards pushing hand
🫸 Rightwards pushing hand
👌 oK hand
🤌 Pinched fingers
🤏 Pinching hand
✌ Victory hand
🤞 Crossed fingers
🫰 Hand with index finger and thumb crossed
🤟 Love-you gesture
🤘 Sign of the horns
🤙 Call me hand
👈 Backhand index pointing left
👉 Backhand index pointing right
👆 Backhand index pointing up
🖕 Middle finger
👇 Backhand index pointing down
☝ Index pointing up
🫵 Index pointing at the viewer
👍 Thumbs up
👎 Thumbs down
✊ Raised fist
👊 Oncoming fist
🤛 Left-facing fist
🤜 Right-facing fist
👏 Clapping hands
🙌 Raising hands
🫶 Heart hands
👐 Open hands
🤲 Palms up together
🤝 Handshake
🙏 Folded hands
✍ Writing hand
💅 Nail polish
🤳 Selfie
💪 Flexed biceps
🦾 Mechanical arm
🦿 Mechanical leg
🦵 Leg
🦶 Foot
👂 Ear
🦻 Ear with hearing aid
👃 Nose
🧠 Brain
🫀 Anatomical heart
🫁 Lungs
🦷 Tooth
🦴 Bone
👀 Eyes
👁 Eye
👅 Tongue
👄 Mouth
🫦 Biting lip
👶 Baby
🧒 Child
👦 Boy
👧 Girl
🧑 Person
👱 Person: blond hair
👨 Man
🧔 Person: beard
🧔‍♂️ man: beard
🧔‍♀️ woman: beard
👨‍🦰 man: red hair
👨‍🦱 man: curly hair
👨‍🦳 man: white hair
👨‍🦲 man: bald
👩 Woman
👩‍🦰 woman: red hair
🧑‍🦰 person: red hair
👩‍🦱 woman: curly hair
🧑‍🦱 person: curly hair
👩‍🦳 woman: white hair
🧑‍🦳 person: white hair
👩‍🦲 woman: bald
🧑‍🦲 person: bald
👱‍♀️ woman: blond hair
👱‍♂️ man: blond hair
🧓 Older person
👴 Old man
👵 Old woman
🙍 Person frowning
🙍‍♂️ man frowning
🙍‍♀️ woman frowning
🙎 Person pouting
🙎‍♂️ man pouting
🙎‍♀️ woman pouting
🙅 Person gesturing NO
🙅‍♂️ man gesturing NO
🙅‍♀️ woman gesturing NO
🙆 Person gesturing OK
🙆‍♂️ man gesturing OK
🙆‍♀️ woman gesturing OK
💁 Person tipping hand
💁‍♂️ man tipping hand
💁‍♀️ woman tipping hand
🙋 Person raising hand
🙋‍♂️ man raising hand
🙋‍♀️ woman raising hand
🧏 Deaf person
🧏‍♂️ deaf man
🧏‍♀️ deaf woman
🙇 Person bowing
🙇‍♂️ man bowing
🙇‍♀️ woman bowing
🤦 Person facepalming
🤦‍♂️ man facepalming
🤦‍♀️ woman facepalming
🤷 Person shrugging
🤷‍♂️ man shrugging
🤷‍♀️ woman shrugging
🧑‍⚕️ health worker
👨‍⚕️ man health worker
👩‍⚕️ woman health worker
🧑‍🎓 student
👨‍🎓 man student
👩‍🎓 woman student
🧑‍🏫 teacher
👨‍🏫 man teacher
👩‍🏫 woman teacher
🧑‍⚖️ judge
👨‍⚖️ man judge
👩‍⚖️ woman judge
🧑‍🌾 farmer
👨‍🌾 man farmer
👩‍🌾 woman farmer
🧑‍🍳 cook
👨‍🍳 man cook
👩‍🍳 woman cook
🧑‍🔧 mechanic
👨‍🔧 man mechanic
👩‍🔧 woman mechanic
🧑‍🏭 factory worker
👨‍🏭 man factory worker
👩‍🏭 woman factory worker
🧑‍💼 office worker
👨‍💼 man office worker
👩‍💼 woman office worker
🧑‍🔬 scientist
👨‍🔬 man scientist
👩‍🔬 woman scientist
🧑‍💻 technologist
👨‍💻 man technologist
👩‍💻 woman technologist
🧑‍🎤 singer
👨‍🎤 man singer
👩‍🎤 woman singer
🧑‍🎨 artist
👨‍🎨 man artist
👩‍🎨 woman artist
🧑‍✈️ pilot
👨‍✈️ man pilot
👩‍✈️ woman pilot
🧑‍🚀 astronaut
👨‍🚀 man astronaut
👩‍🚀 woman astronaut
🧑‍🚒 firefighter
👨‍🚒 man firefighter
👩‍🚒 woman firefighter
👮 Police officer
👮‍♂️ man police officer
👮‍♀️ woman police officer
🕵 Detective
🕵️‍♂️ man detective
🕵️‍♀️ woman detective
💂 Guard
💂‍♂️ man guard
💂‍♀️ woman guard
🥷 Ninja
👷 Construction worker
👷‍♂️ man construction worker
👷‍♀️ woman construction worker
🫅 Person with crown
🤴 Prince
👸 Princess
👳 Person wearing turban
👳‍♂️ man wearing turban
👳‍♀️ woman wearing turban
👲 Person with skullcap
🧕 Woman with headscarf
🤵 Person in tuxedo
🤵‍♂️ man in tuxedo
🤵‍♀️ woman in tuxedo
👰 Person with veil
👰‍♂️ man with veil
👰‍♀️ woman with veil
🤰 Pregnant woman
🫃 Pregnant man
🫄 Pregnant person
🤱 Breast-feeding
👩‍🍼 woman feeding baby
👨‍🍼 man feeding baby
🧑‍🍼 person feeding baby
👼 Baby angel
🎅 santa Claus
🤶 mrs. Claus
🧑‍🎄 Mx Claus
🦸 Superhero
🦸‍♂️ man superhero
🦸‍♀️ woman superhero
🦹 Supervillain
🦹‍♂️ man supervillain
🦹‍♀️ woman supervillain
🧙 Mage
🧙‍♂️ man mage
🧙‍♀️ woman mage
🧚 Fairy
🧚‍♂️ man fairy
🧚‍♀️ woman fairy
🧛 Vampire
🧛‍♂️ man vampire
🧛‍♀️ woman vampire
🧜 Merperson
🧜‍♂️ merman
🧜‍♀️ mermaid
🧝 Elf
🧝‍♂️ man elf
🧝‍♀️ woman elf
🧞 Genie
🧞‍♂️ man genie
🧞‍♀️ woman genie
🧟 Zombie
🧟‍♂️ man zombie
🧟‍♀️ woman zombie
🧌 Troll
💆 Person getting massage
💆‍♂️ man getting massage
💆‍♀️ woman getting massage
💇 Person getting haircut
💇‍♂️ man getting haircut
💇‍♀️ woman getting haircut
🚶 Person walking
🚶‍♂️ man walking
🚶‍♀️ woman walking
🚶‍➡️ person walking facing right
🚶‍♀️‍➡️ woman walking facing right
🚶‍♂️‍➡️ man walking facing right
🧍 Person standing
🧍‍♂️ man standing
🧍‍♀️ woman standing
🧎 Person kneeling
🧎‍♂️ man kneeling
🧎‍♀️ woman kneeling
🧎‍➡️ person kneeling facing right
🧎‍♀️‍➡️ woman kneeling facing right
🧎‍♂️‍➡️ man kneeling facing right
🧑‍🦯 person with white cane
🧑‍🦯‍➡️ person with white cane facing right
👨‍🦯 man with white cane
👨‍🦯‍➡️ man with white cane facing right
👩‍🦯 woman with white cane
👩‍🦯‍➡️ woman with white cane facing right
🧑‍🦼 person in motorized wheelchair
🧑‍🦼‍➡️ person in motorized wheelchair facing right
👨‍🦼 man in motorized wheelchair
👨‍🦼‍➡️ man in motorized wheelchair facing right
👩‍🦼 woman in motorized wheelchair
👩‍🦼‍➡️ woman in motorized wheelchair facing right
🧑‍🦽 person in manual wheelchair
🧑‍🦽‍➡️ person in manual wheelchair facing right
👨‍🦽 man in manual wheelchair
👨‍🦽‍➡️ man in manual wheelchair facing right
👩‍🦽 woman in manual wheelchair
👩‍🦽‍➡️ woman in manual wheelchair facing right
🏃 Person running
🏃‍♂️ man running
🏃‍♀️ woman running
🏃‍➡️ person running facing right
🏃‍♀️‍➡️ woman running facing right
🏃‍♂️‍➡️ man running facing right
💃 Woman dancing
🕺 Man dancing
🕴 Person in suit levitating
👯 People with bunny ears
👯‍♂️ men with bunny ears
👯‍♀️ women with bunny ears
🧖 Person in steamy room
🧖‍♂️ man in steamy room
🧖‍♀️ woman in steamy room
🧗 Person climbing
🧗‍♂️ man climbing
🧗‍♀️ woman climbing
🤺 Person fencing
🏇 Horse racing
⛷ Skier
🏂 Snowboarder
🏌 Person golfing
🏌️‍♂️ man golfing
🏌️‍♀️ woman golfing
🏄 Person surfing
🏄‍♂️ man surfing
🏄‍♀️ woman surfing
🚣 Person rowing boat
🚣‍♂️ man rowing boat
🚣‍♀️ woman rowing boat
🏊 Person swimming
🏊‍♂️ man swimming
🏊‍♀️ woman swimming
⛹ Person bouncing ball
⛹️‍♂️ man bouncing ball
⛹️‍♀️ woman bouncing ball
🏋 Person lifting weights
🏋️‍♂️ man lifting weights
🏋️‍♀️ woman lifting weights
🚴 Person biking
🚴‍♂️ man biking
🚴‍♀️ woman biking
🚵 Person mountain biking
🚵‍♂️ man mountain biking
🚵‍♀️ woman mountain biking
🤸 Person cartwheeling
🤸‍♂️ man cartwheeling
🤸‍♀️ woman cartwheeling
🤼 People wrestling
🤼‍♂️ men wrestling
🤼‍♀️ women wrestling
🤽 Person playing water polo
🤽‍♂️ man playing water polo
🤽‍♀️ woman playing water polo
🤾 Person playing handball
🤾‍♂️ man playing handball
🤾‍♀️ woman playing handball
🤹 Person juggling
🤹‍♂️ man juggling
🤹‍♀️ woman juggling
🧘 Person in lotus position
🧘‍♂️ man in lotus position
🧘‍♀️ woman in lotus position
🛀 Person taking bath
🛌 Person in bed
🧑‍🤝‍🧑 people holding hands
👭 Women holding hands
👫 Woman and man holding hands
👬 Men holding hands
💏 Kiss
👩‍❤️‍💋‍👨 kiss: woman, man
👨‍❤️‍💋‍👨 kiss: man, man
👩‍❤️‍💋‍👩 kiss: woman, woman
💑 Couple with heart
👩‍❤️‍👨 couple with heart: woman, man
👨‍❤️‍👨 couple with heart: man, man
👩‍❤️‍👩 couple with heart: woman, woman
👨‍👩‍👦 family: man, woman, boy
👨‍👩‍👧 family: man, woman, girl
👨‍👩‍👧‍👦 family: man, woman, girl, boy
👨‍👩‍👦‍👦 family: man, woman, boy, boy
👨‍👩‍👧‍👧 family: man, woman, girl, girl
👨‍👨‍👦 family: man, man, boy
👨‍👨‍👧 family: man, man, girl
👨‍👨‍👧‍👦 family: man, man, girl, boy
👨‍👨‍👦‍👦 family: man, man, boy, boy
👨‍👨‍👧‍👧 family: man, man, girl, girl
👩‍👩‍👦 family: woman, woman, boy
👩‍👩‍👧 family: woman, woman, girl
👩‍👩‍👧‍👦 family: woman, woman, girl, boy
👩‍👩‍👦‍👦 family: woman, woman, boy, boy
👩‍👩‍👧‍👧 family: woman, woman, girl, girl
👨‍👦 family: man, boy
👨‍👦‍👦 family: man, boy, boy
👨‍👧 family: man, girl
👨‍👧‍👦 family: man, girl, boy
👨‍👧‍👧 family: man, girl, girl
👩‍👦 family: woman, boy
👩‍👦‍👦 family: woman, boy, boy
👩‍👧 family: woman, girl
👩‍👧‍👦 family: woman, girl, boy
👩‍👧‍👧 family: woman, girl, girl
🗣 Speaking head
👤 Bust in silhouette
👥 Busts in silhouette
🫂 People hugging
👪 Family
🧑‍🧑‍🧒 family: adult, adult, child
🧑‍🧑‍🧒‍🧒 family: adult, adult, child, child
🧑‍🧒 family: adult, child
🧑‍🧒‍🧒 family: adult, child, child
👣 Footprints
🫆 ⊛ fingerprint
🦰 Red hair
🦱 Curly hair
🦳 White hair
🦲 Bald
🐵 Monkey face
🐒 Monkey
🦍 Gorilla
🦧 Orangutan
🐶 Dog face
🐕 Dog
🦮 Guide dog
🐕‍🦺 service dog
🐩 Poodle
🐺 Wolf
🦊 Fox
🦝 Raccoon
🐱 Cat face
🐈 Cat
🐈‍⬛ black cat
🦁 Lion
🐯 Tiger face
🐅 Tiger
🐆 Leopard
🐴 Horse face
🫎 Moose
🫏 Donkey
🐎 Horse
🦄 Unicorn
🦓 Zebra
🦌 Deer
🦬 Bison
🐮 Cow face
🐂 Ox
🐃 Water buffalo
🐄 Cow
🐷 Pig face
🐖 Pig
🐗 Boar
🐽 Pig nose
🐏 Ram
🐑 Ewe
🐐 Goat
🐪 Camel
🐫 Two-hump camel
🦙 Llama
🦒 Giraffe
🐘 Elephant
🦣 Mammoth
🦏 Rhinoceros
🦛 Hippopotamus
🐭 Mouse face
🐁 Mouse
🐀 Rat
🐹 Hamster
🐰 Rabbit face
🐇 Rabbit
🐿 Chipmunk
🦫 Beaver
🦔 Hedgehog
🦇 Bat
🐻 Bear
🐻‍❄️ polar bear
🐨 Koala
🐼 Panda
🦥 Sloth
🦦 Otter
🦨 Skunk
🦘 Kangaroo
🦡 Badger
🐾 Paw prints
🦃 Turkey
🐔 Chicken
🐓 Rooster
🐣 Hatching chick
🐤 Baby chick
🐥 Front-facing baby chick
🐦 Bird
🐧 Penguin
🕊 Dove
🦅 Eagle
🦆 Duck
🦢 Swan
🦉 Owl
🦤 Dodo
🪶 Feather
🦩 Flamingo
🦚 Peacock
🦜 Parrot
🪽 Wing
🐦‍⬛ black bird
🪿 Goose
🐦‍🔥 phoenix
🐸 Frog
🐊 Crocodile
🐢 Turtle
🦎 Lizard
🐍 Snake
🐲 Dragon face
🐉 Dragon
🦕 Sauropod
🦖 t-Rex
🐳 Spouting whale
🐋 Whale
🐬 Dolphin
🦭 Seal
🐟 Fish
🐠 Tropical fish
🐡 Blowfish
🦈 Shark
🐙 Octopus
🐚 Spiral shell
🪸 Coral
🪼 Jellyfish
🦀 Crab
🦞 Lobster
🦐 Shrimp
🦑 Squid
🦪 Oyster
🐌 Snail
🦋 Butterfly
🐛 Bug
🐜 Ant
🐝 Honeybee
🪲 Beetle
🐞 Lady beetle
🦗 Cricket
🪳 Cockroach
🕷 Spider
🕸 Spider web
🦂 Scorpion
🦟 Mosquito
🪰 Fly
🪱 Worm
🦠 Microbe
💐 Bouquet
🌸 Cherry blossom
💮 White flower
🪷 Lotus
🏵 Rosette
🌹 Rose
🥀 Wilted flower
🌺 Hibiscus
🌻 Sunflower
🌼 Blossom
🌷 Tulip
🪻 Hyacinth
🌱 Seedling
🪴 Potted plant
🌲 Evergreen tree
🌳 Deciduous tree
🌴 Palm tree
🌵 Cactus
🌾 Sheaf of rice
🌿 Herb
☘ Shamrock
🍀 Four leaf clover
🍁 Maple leaf
🍂 Fallen leaf
🍃 Leaf fluttering in wind
🪹 Empty nest
🪺 Nest with eggs
🍄 Mushroom
🪾 ⊛ leafless tree
🍇 Grapes
🍈 Melon
🍉 Watermelon
🍊 Tangerine
🍋 Lemon
🍋‍🟩 lime
🍌 Banana
🍍 Pineapple
🥭 Mango
🍎 Red apple
🍏 Green apple
🍐 Pear
🍑 Peach
🍒 Cherries
🍓 Strawberry
🫐 Blueberries
🥝 Kiwi fruit
🍅 Tomato
🫒 Olive
🥥 Coconut
🥑 Avocado
🍆 Eggplant
🥔 Potato
🥕 Carrot
🌽 Ear of corn
🌶 Hot pepper
🫑 Bell pepper
🥒 Cucumber
🥬 Leafy green
🥦 Broccoli
🧄 Garlic
🧅 Onion
🥜 Peanuts
🫘 Beans
🌰 Chestnut
🫚 Ginger root
🫛 Pea pod
🍄‍🟫 brown mushroom
🫜 ⊛ root vegetable
🍞 Bread
🥐 Croissant
🥖 Baguette bread
🫓 Flatbread
🥨 Pretzel
🥯 Bagel
🥞 Pancakes
🧇 Waffle
🧀 Cheese wedge
🍖 Meat on bone
🍗 Poultry leg
🥩 Cut of meat
🥓 Bacon
🍔 Hamburger
🍟 French fries
🍕 Pizza
🌭 Hot dog
🥪 Sandwich
🌮 Taco
🌯 Burrito
🫔 Tamale
🥙 Stuffed flatbread
🧆 Falafel
🥚 Egg
🍳 Cooking
🥘 Shallow pan of food
🍲 Pot of food
🫕 Fondue
🥣 Bowl with spoon
🥗 Green salad
🍿 Popcorn
🧈 Butter
🧂 Salt
🥫 Canned food
🍱 Bento box
🍘 Rice cracker
🍙 Rice ball
🍚 Cooked rice
🍛 Curry rice
🍜 Steaming bowl
🍝 Spaghetti
🍠 Roasted sweet potato
🍢 Oden
🍣 Sushi
🍤 Fried shrimp
🍥 Fish cake with swirl
🥮 Moon cake
🍡 Dango
🥟 Dumpling
🥠 Fortune cookie
🥡 Takeout box
🍦 Soft ice cream
🍧 Shaved ice
🍨 Ice cream
🍩 Doughnut
🍪 Cookie
🎂 Birthday cake
🍰 Shortcake
🧁 Cupcake
🥧 Pie
🍫 Chocolate bar
🍬 Candy
🍭 Lollipop
🍮 Custard
🍯 Honey pot
🍼 Baby bottle
🥛 Glass of milk
☕ Hot beverage
🫖 Teapot
🍵 Teacup without handle
🍶 Sake
🍾 Bottle with popping cork
🍷 Wine glass
🍸 Cocktail glass
🍹 Tropical drink
🍺 Beer mug
🍻 Clinking beer mugs
🥂 Clinking glasses
🥃 Tumbler glass
🫗 Pouring liquid
🥤 Cup with straw
🧋 Bubble tea
🧃 Beverage box
🧉 Mate
🧊 Ice
🥢 Chopsticks
🍽 Fork and knife with plate
🍴 Fork and knife
🥄 Spoon
🔪 Kitchen knife
🫙 Jar
🏺 Amphora
🌍 Globe showing Europe-Africa
🌎 Globe showing Americas
🌏 Globe showing Asia-Australia
🌐 Globe with meridians
🗺 World map
🗾 Map of Japan
🧭 Compass
🏔 Snow-capped mountain
⛰ Mountain
🌋 Volcano
🗻 Mount fuji
🏕 Camping
🏖 Beach with umbrella
🏜 Desert
🏝 Desert island
🏞 National park
🏟 Stadium
🏛 Classical building
🏗 Building construction
🧱 Brick
🪨 Rock
🪵 Wood
🛖 Hut
🏘 Houses
🏚 Derelict house
🏠 House
🏡 House with garden
🏢 Office building
🏣 japanese post office
🏤 Post office
🏥 Hospital
🏦 Bank
🏨 Hotel
🏩 Love hotel
🏪 Convenience store
🏫 School
🏬 Department store
🏭 Factory
🏯 japanese castle
🏰 Castle
💒 Wedding
🗼 tokyo tower
🗽 statue of Liberty
⛪ Church
🕌 Mosque
🛕 Hindu temple
🕍 Synagogue
⛩ Shinto shrine
🕋 Kaaba
⛲ Fountain
⛺ Tent
🌁 Foggy
🌃 Night with stars
🏙 Cityscape
🌄 Sunrise over mountains
🌅 Sunrise
🌆 Cityscape at dusk
🌇 Sunset
🌉 Bridge at night
♨ Hot springs
🎠 Carousel horse
🛝 Playground slide
🎡 Ferris wheel
🎢 Roller coaster
💈 Barber pole
🎪 Circus tent
🚂 Locomotive
🚃 Railway car
🚄 High-speed train
🚅 Bullet train
🚆 Train
🚇 Metro
🚈 Light rail
🚉 Station
🚊 Tram
🚝 Monorail
🚞 Mountain railway
🚋 Tram car
🚌 Bus
🚍 Oncoming bus
🚎 Trolleybus
🚐 Minibus
🚑 Ambulance
🚒 Fire engine
🚓 Police car
🚔 Oncoming police car
🚕 Taxi
🚖 Oncoming taxi
🚗 Automobile
🚘 Oncoming automobile
🚙 Sport utility vehicle
🛻 Pickup truck
🚚 Delivery truck
🚛 Articulated lorry
🚜 Tractor
🏎 Racing car
🏍 Motorcycle
🛵 Motor scooter
🦽 Manual wheelchair
🦼 Motorized wheelchair
🛺 Auto rickshaw
🚲 Bicycle
🛴 Kick scooter
🛹 Skateboard
🛼 Roller skate
🚏 Bus stop
🛣 Motorway
🛤 Railway track
🛢 Oil drum
⛽ Fuel pump
🛞 Wheel
🚨 Police car light
🚥 Horizontal traffic light
🚦 Vertical traffic light
🛑 Stop sign
🚧 Construction
⚓ Anchor
🛟 Ring buoy
⛵ Sailboat
🛶 Canoe
🚤 Speedboat
🛳 Passenger ship
⛴ Ferry
🛥 Motor boat
🚢 Ship
✈ Airplane
🛩 Small airplane
🛫 Airplane departure
🛬 Airplane arrival
🪂 Parachute
💺 Seat
🚁 Helicopter
🚟 Suspension railway
🚠 Mountain cableway
🚡 Aerial tramway
🛰 Satellite
🚀 Rocket
🛸 Flying saucer
🛎 Bellhop bell
🧳 Luggage
⌛ Hourglass done
⏳ Hourglass not done
⌚ Watch
⏰ Alarm clock
⏱ Stopwatch
⏲ Timer clock
🕰 Mantelpiece clock
🕛 Twelve o’clock
🕧 Twelve-thirty
🕐 One o’clock
🕜 One-thirty
🕑 Two o’clock
🕝 Two-thirty
🕒 Three o’clock
🕞 Three-thirty
🕓 Four o’clock
🕟 Four-thirty
🕔 Five o’clock
🕠 Five-thirty
🕕 Six o’clock
🕡 Six-thirty
🕖 Seven o’clock
🕢 Seven-thirty
🕗 Eight o’clock
🕣 Eight-thirty
🕘 Nine o’clock
🕤 Nine-thirty
🕙 Ten o’clock
🕥 Ten-thirty
🕚 Eleven o’clock
🕦 Eleven-thirty
🌑 New moon
🌒 Waxing crescent moon
🌓 First quarter moon
🌔 Waxing gibbous moon
🌕 Full moon
🌖 Waning gibbous moon
🌗 Last quarter moon
🌘 Waning crescent moon
🌙 Crescent moon
🌚 New moon face
🌛 First quarter moon face
🌜 Last quarter moon face
🌡 Thermometer
☀ Sun
🌝 Full moon face
🌞 Sun with face
🪐 Ringed planet
⭐ Star
🌟 Glowing star
🌠 Shooting star
🌌 Milky way
☁ Cloud
⛅ Sun behind cloud
⛈ Cloud with lightning and rain
🌤 Sun behind small cloud
🌥 Sun behind large cloud
🌦 Sun behind rain cloud
🌧 Cloud with rain
🌨 Cloud with snow
🌩 Cloud with lightning
🌪 Tornado
🌫 Fog
🌬 Wind face
🌀 Cyclone
🌈 Rainbow
🌂 Closed umbrella
☂ Umbrella
☔ Umbrella with rain drops
⛱ Umbrella on ground
⚡ High voltage
❄ Snowflake
☃ Snowman
⛄ Snowman without snow
☄ Comet
🔥 Fire
💧 Droplet
🌊 Water wave
🎃 Jack-o-lantern
🎄 christmas tree
🎆 Fireworks
🎇 Sparkler
🧨 Firecracker
✨ Sparkles
🎈 Balloon
🎉 Party popper
🎊 Confetti ball
🎋 Tanabata tree
🎍 Pine decoration
🎎 japanese dolls
🎏 Carp streamer
🎐 Wind chime
🎑 Moon viewing ceremony
🧧 Red envelope
🎀 Ribbon
🎁 Wrapped gift
🎗 Reminder ribbon
🎟 Admission tickets
🎫 Ticket
🎖 Military medal
🏆 Trophy
🏅 Sports medal
🥇 1st place medal
🥈 2nd place medal
🥉 3rd place medal
⚽ Soccer ball
⚾ Baseball
🥎 Softball
🏀 Basketball
🏐 Volleyball
🏈 American football
🏉 Rugby football
🎾 Tennis
🥏 Flying disc
🎳 Bowling
🏏 Cricket game
🏑 Field hockey
🏒 Ice hockey
🥍 Lacrosse
🏓 Ping pong
🏸 Badminton
🥊 Boxing glove
🥋 Martial arts uniform
🥅 Goal net
⛳ Flag in hole
⛸ Ice skate
🎣 Fishing pole
🤿 Diving mask
🎽 Running shirt
🎿 Skis
🛷 Sled
🥌 Curling stone
🎯 Bullseye
🪀 Yo-yo
🪁 Kite
🔫 Water pistol
🎱 Pool 8 ball
🔮 Crystal ball
🪄 Magic wand
🎮 Video game
🕹 Joystick
🎰 Slot machine
🎲 Game die
🧩 Puzzle piece
🧸 Teddy bear
🪅 Piñata
🪩 Mirror ball
🪆 Nesting dolls
♠ Spade suit
♥ Heart suit
♦ Diamond suit
♣ Club suit
♟ Chess pawn
🃏 Joker
🀄 Mahjong red dragon
🎴 Flower playing cards
🎭 Performing arts
🖼 Framed picture
🎨 Artist palette
🧵 Thread
🪡 Sewing needle
🧶 Yarn
🪢 Knot
👓 Glasses
🕶 Sunglasses
🥽 Goggles
🥼 Lab coat
🦺 Safety vest
👔 Necktie
👕 T-shirt
👖 Jeans
🧣 Scarf
🧤 Gloves
🧥 Coat
🧦 Socks
👗 Dress
👘 Kimono
🥻 Sari
🩱 One-piece swimsuit
🩲 Briefs
🩳 Shorts
👙 Bikini
👚 Woman’s clothes
🪭 Folding hand fan
👛 Purse
👜 Handbag
👝 Clutch bag
🛍 Shopping bags
🎒 Backpack
🩴 Thong sandal
👞 Man’s shoe
👟 Running shoe
🥾 Hiking boot
🥿 Flat shoe
👠 High-heeled shoe
👡 Woman’s sandal
🩰 Ballet shoes
👢 Woman’s boot
🪮 Hair pick
👑 Crown
👒 Woman’s hat
🎩 Top hat
🎓 Graduation cap
🧢 Billed cap
🪖 Military helmet
⛑ Rescue worker’s helmet
📿 Prayer beads
💄 Lipstick
💍 Ring
💎 Gem stone
🔇 Muted speaker
🔈 Speaker low volume
🔉 Speaker medium volume
🔊 Speaker high volume
📢 Loudspeaker
📣 Megaphone
📯 Postal horn
🔔 Bell
🔕 Bell with slash
🎼 Musical score
🎵 Musical note
🎶 Musical notes
🎙 Studio microphone
🎚 Level slider
🎛 Control knobs
🎤 Microphone
🎧 Headphone
📻 Radio
🎷 Saxophone
🪗 Accordion
🎸 Guitar
🎹 Musical keyboard
🎺 Trumpet
🎻 Violin
🪕 Banjo
🥁 Drum
🪘 Long drum
🪇 Maracas
🪈 Flute
🪉 ⊛ harp
📱 Mobile phone
📲 Mobile phone with arrow
☎ Telephone
📞 Telephone receiver
📟 Pager
📠 Fax machine
🔋 Battery
🪫 Low battery
🔌 Electric plug
💻 Laptop
🖥 Desktop computer
🖨 Printer
⌨ Keyboard
🖱 Computer mouse
🖲 Trackball
💽 Computer disk
💾 Floppy disk
💿 Optical disk
📀 Dvd
🧮 Abacus
🎥 Movie camera
🎞 Film frames
📽 Film projector
🎬 Clapper board
📺 Television
📷 Camera
📸 Camera with flash
📹 Video camera
📼 Videocassette
🔍 Magnifying glass tilted left
🔎 Magnifying glass tilted right
🕯 Candle
💡 Light bulb
🔦 Flashlight
🏮 Red paper lantern
🪔 Diya lamp
📔 Notebook with decorative cover
📕 Closed book
📖 Open book
📗 Green book
📘 Blue book
📙 Orange book
📚 Books
📓 Notebook
📒 Ledger
📃 Page with curl
📜 Scroll
📄 Page facing up
📰 Newspaper
🗞 Rolled-up newspaper
📑 Bookmark tabs
🔖 Bookmark
🏷 Label
💰 Money bag
🪙 Coin
💴 Yen banknote
💵 Dollar banknote
💶 Euro banknote
💷 Pound banknote
💸 Money with wings
💳 Credit card
🧾 Receipt
💹 Chart increasing with yen
✉ Envelope
📧 E-mail
📨 Incoming envelope
📩 Envelope with arrow
📤 Outbox tray
📥 Inbox tray
📦 Package
📫 Closed mailbox with raised flag
📪 Closed mailbox with lowered flag
📬 Open mailbox with raised flag
📭 Open mailbox with lowered flag
📮 Postbox
🗳 Ballot box with ballot
✏ Pencil
✒ Black nib
🖋 Fountain pen
🖊 Pen
🖌 Paintbrush
🖍 Crayon
📝 Memo
💼 Briefcase
📁 File folder
📂 Open file folder
🗂 Card index dividers
📅 Calendar
📆 Tear-off calendar
🗒 Spiral notepad
🗓 Spiral calendar
📇 Card index
📈 Chart increasing
📉 Chart decreasing
📊 Bar chart
📋 Clipboard
📌 Pushpin
📍 Round pushpin
📎 Paperclip
🖇 Linked paperclips
📏 Straight ruler
📐 Triangular ruler
✂ Scissors
🗃 Card file box
🗄 File cabinet
🗑 Wastebasket
🔒 Locked
🔓 Unlocked
🔏 Locked with pen
🔐 Locked with key
🔑 Key
🗝 Old key
🔨 Hammer
🪓 Axe
⛏ Pick
⚒ Hammer and pick
🛠 Hammer and wrench
🗡 Dagger
⚔ Crossed swords
💣 Bomb
🪃 Boomerang
🏹 Bow and arrow
🛡 Shield
🪚 Carpentry saw
🔧 Wrench
🪛 Screwdriver
🔩 Nut and bolt
⚙ Gear
🗜 Clamp
⚖ Balance scale
🦯 White cane
🔗 Link
⛓️‍💥 broken chain
⛓ Chains
🪝 Hook
🧰 Toolbox
🧲 Magnet
🪜 Ladder
🪏 ⊛ shovel
⚗ Alembic
🧪 Test tube
🧫 Petri dish
🧬 Dna
🔬 Microscope
🔭 Telescope
📡 Satellite antenna
💉 Syringe
🩸 Drop of blood
💊 Pill
🩹 Adhesive bandage
🩼 Crutch
🩺 Stethoscope
🩻 X-ray
🚪 Door
🛗 Elevator
🪞 Mirror
🪟 Window
🛏 Bed
🛋 Couch and lamp
🪑 Chair
🚽 Toilet
🪠 Plunger
🚿 Shower
🛁 Bathtub
🪤 Mouse trap
🪒 Razor
🧴 Lotion bottle
🧷 Safety pin
🧹 Broom
🧺 Basket
🧻 Roll of paper
🪣 Bucket
🧼 Soap
🫧 Bubbles
🪥 Toothbrush
🧽 Sponge
🧯 Fire extinguisher
🛒 Shopping cart
🚬 Cigarette
⚰ Coffin
🪦 Headstone
⚱ Funeral urn
🧿 Nazar amulet
🪬 Hamsa
🗿 Moai
🪧 Placard
🪪 Identification card
🏧 aTM sign
🚮 Litter in bin sign
🚰 Potable water
♿ Wheelchair symbol
🚹 Men’s room
🚺 Women’s room
🚻 Restroom
🚼 Baby symbol
🚾 Water closet
🛂 Passport control
🛃 Customs
🛄 Baggage claim
🛅 Left luggage
⚠ Warning
🚸 Children crossing
⛔ No entry
🚫 Prohibited
🚳 No bicycles
🚭 No smoking
🚯 No littering
🚱 Non-potable water
🚷 No pedestrians
📵 No mobile phones
🔞 No one under eighteen
☢ Radioactive
☣ Biohazard
⬆ Up arrow
↗ Up-right arrow
➡ Right arrow
↘ Down-right arrow
⬇ Down arrow
↙ Down-left arrow
⬅ Left arrow
↖ Up-left arrow
↕ Up-down arrow
↔ Left-right arrow
↩ Right arrow curving left
↪ Left arrow curving right
⤴ Right arrow curving up
⤵ Right arrow curving down
🔃 Clockwise vertical arrows
🔄 Counterclockwise arrows button
🔙 bACK arrow
🔚 eND arrow
🔛 oN! arrow
🔜 sOON arrow
🔝 tOP arrow
🛐 Place of worship
⚛ Atom symbol
🕉 Om
✡ Star of David
☸ Wheel of dharma
☯ Yin yang
✝ Latin cross
☦ Orthodox cross
☪ Star and crescent
☮ Peace symbol
🕎 Menorah
🔯 Dotted six-pointed star
🪯 Khanda
♈ aries
♉ taurus
♊ gemini
♋ cancer
♌ leo
♍ virgo
♎ libra
♏ scorpio
♐ sagittarius
♑ capricorn
♒ aquarius
♓ pisces
⛎ ophiuchus
🔀 Shuffle tracks button
🔁 Repeat button
🔂 Repeat single button
▶ Play button
⏩ Fast-forward button
⏭ Next track button
⏯ Play or pause button
◀ Reverse button
⏪ Fast reverse button
⏮ Last track button
🔼 Upwards button
⏫ Fast up button
🔽 Downwards button
⏬ Fast down button
⏸ Pause button
⏹ Stop button
⏺ Record button
⏏ Eject button
🎦 Cinema
🔅 Dim button
🔆 Bright button
📶 Antenna bars
🛜 Wireless
📳 Vibration mode
📴 Mobile phone off
♀ Female sign
♂ Male sign
⚧ Transgender symbol
✖ Multiply
➕ Plus
➖ Minus
➗ Divide
🟰 Heavy equals sign
♾ Infinity
‼ Double exclamation mark
⁉ Exclamation question mark
❓ Red question mark
❔ White question mark
❕ White exclamation mark
❗ Red exclamation mark
〰 Wavy dash
💱 Currency exchange
💲 Heavy dollar sign
⚕ Medical symbol
♻ Recycling symbol
⚜ Fleur-de-lis
🔱 Trident emblem
📛 Name badge
🔰 japanese symbol for beginner
⭕ Hollow red circle
✅ Check mark button
☑ Check box with check
✔ Check mark
❌ Cross mark
❎ Cross mark button
➰ Curly loop
➿ Double curly loop
〽 Part alternation mark
✳ Eight-spoked asterisk
✴ Eight-pointed star
❇ Sparkle
© Copyright
® Registered
🔴 Red circle
🟠 Orange circle
🟡 Yellow circle
🟢 Green circle
🔵 Blue circle
🟣 Purple circle
🟤 Brown circle
⚫ Black circle
⚪ White circle
🟥 Red square
🟧 Orange square
🟨 Yellow square
🟩 Green square
🟦 Blue square
🟪 Purple square
🟫 Brown square
⬛ Black large square
⬜ White large square
🔶 Large orange diamond
🔷 Large blue diamond
🔸 Small orange diamond
🔹 Small blue diamond
🔺 Red triangle pointed up
🔻 Red triangle pointed down
💠 Diamond with a dot
🔘 Radio button
🏁 Chequered flag
🚩 Triangular flag
🎌 Crossed flags
🏴 Black flag
🏳 White flag
